name: cloudipsp_mobile
description: Cloudipsp SDK for Mobile(Android, iOS)
version: 0.0.6
author: Maxim Kozenko
homepage: https://github.com/cloudipsp/flutter-mobile-sdk

environment:
  sdk: '>=2.12.0 <4.0.0'
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^4.2.2
  http: ^1.0.0
  email_validator: ^2.0.1

dev_dependencies:
  build_runner: ^2.1.4
  flutter_test:
    sdk: flutter
  mockito: ^5.0.16


flutter:
  plugin:
    platforms:
      android:
        package: com.cloudipsp.mobile
        pluginClass: CloudipspMobilePlugin
      ios:
        pluginClass: CloudipspMobilePlugin
